name: GitHub Pages Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install 🔧
        run: yarn install

      - name: access to secrets
        run: |
          echo "NEXT_PUBLIC_KAKAO_APP_JS_KEY=$NEXT_PUBLIC_KAKAO_APP_JS_KEY" > .env
        env:
          NEXT_PUBLIC_KAKAO_APP_JS_KEY: ${{secrets.NEXT_PUBLIC_KAKAO_APP_JS_KEY}}

      - name: Build 🔧
        run: yarn build && touch ./out/.nojekyll

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          cname: jejuai.kr
